name: Docker

# 当推送到 main 分支或者打标签时触发构建
on:
  push:
    branches: [ "main", "dev" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  # 使用 GitHub Container Registry
  REGISTRY: ghcr.io
  # 镜像名称，默认为 <github用户名>/<仓库名>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 登录到 GitHub Container Registry
      # 使用 GITHUB_TOKEN 进行认证，这在 Action 中是自动生成的，无需额外配置 Secret
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 提取镜像的元数据（标签、标签等）
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}
          # 自动生成标签：
          # - 如果是分支 push，生成 branch 名称 (e.g., main)
          # - 如果是 tag push，生成 tag 名称 (e.g., v1.0.0)
          # - 总是生成 sha-<commit_hash>
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      # 构建并推送 Docker 镜像
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
